export const TIMEZONES = [
  { value: 'UTC', label: 'UTC' },
  { value: 'Pacific/Midway', label: 'Midway Island, Samoa (UTC-11:00)' },
  { value: 'Pacific/Honolulu', label: 'Hawaii (UTC-10:00)' },
  { value: 'America/Anchorage', label: 'Alaska (UTC-09:00)' },
  { value: 'America/Los_Angeles', label: 'Pacific Time (US & Canada) (UTC-08:00)' },
  { value: 'America/Denver', label: 'Mountain Time (US & Canada) (UTC-07:00)' },
  { value: 'America/Chicago', label: 'Central Time (US & Canada) (UTC-06:00)' },
  { value: 'America/New_York', label: 'Eastern Time (US & Canada) (UTC-05:00)' },
  { value: 'America/Caracas', label: 'Caracas, La Paz (UTC-04:00)' },
  { value: 'America/Halifax', label: 'Atlantic Time (Canada) (UTC-04:00)' },
  { value: 'America/St_Johns', label: 'Newfoundland (UTC-03:30)' },
  { value: 'America/Argentina/Buenos_Aires', label: 'Buenos Aires, Georgetown (UTC-03:00)' },
  { value: 'Atlantic/South_Georgia', label: 'Mid-Atlantic (UTC-02:00)' },
  { value: 'Atlantic/Azores', label: 'Azores, Cape Verde Is. (UTC-01:00)' },
  { value: 'Europe/London', label: 'London, Edinburgh, Dublin, Lisbon (UTC+00:00)' },
  { value: 'Europe/Berlin', label: 'Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna (UTC+01:00)' },
  { value: 'Europe/Athens', label: 'Athens, Bucharest, Istanbul (UTC+02:00)' },
  { value: 'Europe/Moscow', label: 'Moscow, St. Petersburg, Volgograd (UTC+03:00)' },
  { value: 'Asia/Dubai', label: 'Abu Dhabi, Muscat (UTC+04:00)' },
  { value: 'Asia/Kabul', label: 'Kabul (UTC+04:30)' },
  { value: 'Asia/Karachi', label: 'Islamabad, Karachi, Tashkent (UTC+05:00)' },
  { value: 'Asia/Kolkata', label: 'Chennai, Kolkata, Mumbai, New Delhi (UTC+05:30)' },
  { value: 'Asia/Kathmandu', label: 'Kathmandu (UTC+05:45)' },
  { value: 'Asia/Dhaka', label: 'Astana, Dhaka (UTC+06:00)' },
  { value: 'Asia/Rangoon', label: 'Yangon (Rangoon) (UTC+06:30)' },
  { value: 'Asia/Jakarta', label: 'Bangkok, Hanoi, Jakarta (UTC+07:00)' },
  { value: 'Asia/Singapore', label: 'Beijing, Chongqing, Hong Kong, Urumqi (UTC+08:00)' },
  { value: 'Asia/Tokyo', label: 'Osaka, Sapporo, Tokyo (UTC+09:00)' },
  { value: 'Australia/Adelaide', label: 'Adelaide (UTC+09:30)' },
  { value: 'Australia/Sydney', label: 'Canberra, Melbourne, Sydney (UTC+10:00)' },
  { value: 'Asia/Magadan', label: 'Magadan, Solomon Is., New Caledonia (UTC+11:00)' },
  { value: 'Pacific/Auckland', label: 'Auckland, Wellington (UTC+12:00)' },
  { value: 'Pacific/Fiji', label: 'Fiji, Kamchatka, Marshall Is. (UTC+12:00)' },
  { value: 'Pacific/Tongatapu', label: 'Nuku\'alofa (UTC+13:00)' }
];
